<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */
echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */
            echo __('Additional Information') ?></span></legend>

<p>

<div class="field required">
    <label for="estadocivil" class="label"><span><?= __('estadocivil') ?></span></label>
    <div class="control">
        <input type="text" name="estadocivil" id="estadocivil" title="<?= __('estadocivil') ?>" class="input-text" data-validate="{required:true, 'validate-phoneStrict':true}">
    </div>
</div>
</p></fieldset>