<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */
echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */
            echo __('Additional Information') ?></span></legend>

<p>

<div class="field required">
    <label for="ecivil" class="label"><span><?= __('ecivil') ?></span></label>
    <div class="control">
        <input type="text" name="ecivil" id="ecivil" title="<?= __('ecivil') ?>" class="input-text" data-validate="{required:true, 'validate-phoneStrict':true}">
    </div>
</div>
</p></fieldset>