<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */
echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */
            echo __('Additional Information') ?></span></legend>

<p>

<div class="field required">
    <label for="celular" class="label"><span><?= __('celular') ?></span></label>
    <div class="control">
        <input type="text" name="celular" id="celular" title="<?= __('celular') ?>" class="input-text" data-validate="{required:true, 'validate-phoneStrict':true}">
    </div>
</div>
</p></fieldset>