<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */
echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */
            echo __('Additional Information') ?></span></legend>

<p>

<div class="field required">
    <label for="nit" class="label"><span><?= __('Nit') ?></span></label>
    <div class="control">
        <input type="text" name="nit" id="nit"title="<?= __('Nit') ?>" class="input-text" data-validate="{required:true, 'validate-phoneStrict':true}" value="<?= $block->escapeHtmlAttr($block->getFormData()->getnit()) ?>">
    </div>
</div>
</p></fieldset>