<h1>Prueba url</h1>
<!-- <h1>Web services </h1>
<h2>Ping</h2>
<p><?php /* print_r(json_decode($this->ping())); ?></p>
<h2>Consulta de items</h2>
<p><?php print_r(json_decode($this->test_consulta_existencias('AA0778'))); ?></p>
<h2>Consulta de paises</h2>
<p><?php print_r(json_decode($this->consultar_pais('01'))); ?></p>
<h2>Consulta de departamentos</h2>
<p><?php print_r(json_decode($this->consulta_departamentos('01'))); ?></p>
<h2>Consulta de Municipios</h2>
<p><?php print_r(json_decode($this->consulta_municipios('01','001'))); ?></p>
<h2>Consulta de Distritos</h2>
<p><?php print_r(json_decode($this->consulta_distritos('01','001','001'))); ?></p>


<h1>Clientes</h1>
<h2>Crear Cliente</h2>
<p><?php print_r(json_decode($this->crear_cliente('01','01','S','E','N','1','52157594','78689732','CLIENTE APELLIDOS - PRUEBA 1','S'))); ?></p>
<h2>Actualizar Cliente</h2>
<p><?php print_r(json_decode($this->actualizar_cliente('159719201','57906248','LUIS CUMATZ - PRUEBA 23'))); ?></p>
<h2>Consultar Cliente</h1>
<p><?php print_r(json_decode($this->consultar_cliente('159719201'))); ?></p>

<h1>COTIZACIONES</h1>
<h2>Crear</h2>
<p><?php print_r(json_decode($this->crear_cotizacion('01','12','VI01','PRO','E','0-530','P','LUIS CUMATZ',400,7.40,7.40,7.40,'01/01/2018'))); ?></p>
<h2>Actualizar</h2>
<p><?php print_r(json_decode($this->actualizar_cotizacion('01','12','VI01','12508931215','E','P',' MOD NOMBRES',500,'01/01/2018','LOTE 8 SECCION F, ZONA 1, PALIN ESCUINTLA','01','001','001','Casa 35 sec c, colonia las ilusiones, zona 18','2 calle 4 avenida','14-25'))); ?></p>
<h2>Ver</h2>
<p><?php print_r(json_decode($this->ver_cotizacion('01','12','VI01','12508931215'))); ?></p>
<h1>Detalle</h1>
<h2>Crear</h2>
<?php print_r(json_decode($this->crear_detalle('01','12','VI01','12508931215','AA0778',1,235.00,0.00,535.00,'D',1,'N','D'))); ?>
<h2>Actualizar</h2>
<?php print_r(json_decode($this->actualizar_detalle('01','12','VI01','12508931215',1,1,235.00,0.00,535.00,'D',1,'N','D'))); ?>
<h2>Ver</h2>
<?php print_r(json_decode($this->ver_detalle('01','12','VI01','12508931215','1'))); ?>
<h2>Eliminar</h2>
<?php print_r(json_decode($this->eliminar_detalle('01','12','VI01','12508931215','2'))); ?>
<h1>Pedidos</h1>
<h2>Crear</h2>
<?php print_r(json_decode($this->crear_pedido('01','12','VI01','12509241215'))); ?>
<h2>Actualizar</h2>
<?php print_r(json_decode($this->actualizar_pedido('01','12','VI01','12508931215','E','P','LUIS ANTONIO CUMATZ GUERRA',500,0.00,500,7.40,7.40,7.40,'01/01/2018','LOTE 8 SECCION F, ZONA 1, PALIN ESCUINTLA','01','001','001','Casa 35 sec c, colonia las ilusiones, zona 18','2 calle 4 avenida','14-25'))); ?>
<h2>Ver</h2>
<?php print_r(json_decode($this->ver_pedido('01','12','VI01','12508931215'))); ?>
<h1>Detalles Pedidos</h1>
<h2>Crear</h2>
<?php print_r(json_decode($this->crear_detalle_pedido('01','12','VI01','12508931215','AA0778',1,1,235.00,0.00,535.00,'D',1,'N','D'))); ?>
<h2>Actualizar</h2>
<?php print_r(json_decode($this->actualizar_detalle_pedido('01','12','VI01','12508931215',1,1,235.00,0.00,535.00,'D',1,'N','D'))); ?>
<h2>Ver</h2>
<?php print_r(json_decode($this->ver_detalle_pedido('01','12','VI01','12508931215',1))); ?>
<h2>Eliminar</h2>
<?php print_r(json_decode($this->eliminar_detalle_pedido('01','12','VI01','12508931215',1))); ?>
<h2>Factura</h2>
<?php print_r(json_decode($this->factura('01','12','VI01','12508931215'))); */ ?>
<input type="text" name="idcod" id="idcod">
<a onclick="buscarcliente()">Buscar</a>

<div class="notfound"></div>
<div class="resultado">
	<div class="row">		
		<div class="col-md-3">Código de cliente</div>
		<div class="col-md-9" id="cod"></div>
	</div>
	<div class="row">
		<div class="col-md-3">Nombres</div>
		<div class="col-md-9" id="contacto"></div>
	</div>
	<div class="row">
		<div class="col-md-3">Telefono</div>
		<div class="col-md-9" id="telefono"></div>
	</div>
	<div class="row">
		<div class="col-md-3">Estado_civil</div>
		<div class="col-md-9" id="estado"></div>
	</div>
	
</div>-->